### ISSUE TITLE
If set to "private", nodes cannot communicate with master

### ISSUE THREAD

**Issue by Crashthatch** [andypowe11/AWS-Docker-Swarm#1]

**Comment by jweyrich** [comment]
Communication works fine for me. The only thing that caused a problem was the AMI. Swarm seems to require Docker > 1.8, while the AMIs used by the template are < 1.8, causing all the nodes to stay in PENDING state and not joining the cluster. I found it after running the swarm master using the debug flag:

    /usr/bin/docker run --name docker-swarm -d -p 2375:2375 swarm -l debug manage etcd://...

I changed the CoreOS AMI to a newer one (CoreOS-stable-1185.5.0) and it worked properly.

**Comment by andypowe11** [comment]
Thanks. I have now, finally, updated the AMIs I'm using.
